/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BTL_OOP.main.ui.manage;


import BTL_OOP.main.ui.users.DisplayDocumentPanel;
import BTL_OOP.main.ui.users.FindDocumentPanel;
import BTL_OOP.main.ui.users.InFoUserPanel;
import BTL_OOP.main.ui.login.LoginPanel;
import BTL_OOP.main.dao.TransactionDAO;
import BTL_OOP.main.models.user.User;
import BTL_OOP.main.dao.DocumentDAO;
import BTL_OOP.main.models.document.Document;
import BTL_OOP.main.models.document.RenderDocument;
import java.awt.CardLayout;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author thinh
 */
public class ManagePanel extends javax.swing.JPanel {
    private Connection con;
    private JFrame mainFframe;
    private JPanel mainPanel;
    public static User user;
    public static RenderDocument render = new RenderDocument();
    /**
     * Creates new form managePanel
     */
    public ManagePanel(Connection con, JFrame mainFframe, JPanel mainPanel) {
        initComponents();
        this.con = con;
        this.mainFframe = mainFframe;
        this.mainPanel = mainPanel;
    }
    /*
        *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managePane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        userNameManage = new javax.swing.JLabel();
        inFoManageLabel = new javax.swing.JLabel();
        jlabel26 = new javax.swing.JLabel();
        findDocumentJLabel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        titleJLabel5 = new javax.swing.JLabel();
        imageJLabel5 = new javax.swing.JLabel();
        titleJLabel1 = new javax.swing.JLabel();
        titleJLabel6 = new javax.swing.JLabel();
        imageJLabel1 = new javax.swing.JLabel();
        titleJLabel2 = new javax.swing.JLabel();
        imageJLabel2 = new javax.swing.JLabel();
        titleJLabel3 = new javax.swing.JLabel();
        imageJLabel3 = new javax.swing.JLabel();
        imageJLabel6 = new javax.swing.JLabel();
        titleJLabel4 = new javax.swing.JLabel();
        imageJLabel4 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 650));

        managePane.setBackground(new java.awt.Color(244, 244, 244));

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("TRANG CHỦ");
        home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("QUẢN LÝ SÁCH");
        jLabel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("THÊM SÁCH");
        jLabel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        userNameManage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userNameManage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameManage.setText("ACCOUNT");

        inFoManageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BTL_OOP/image/Remove-bg.ai_1729220335126.png"))); // NOI18N
        inFoManageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.SW_RESIZE_CURSOR));
        inFoManageLabel.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        inFoManageLabel.setDisabledIcon(null);
        inFoManageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inFoManageLabel.setIconTextGap(0);
        inFoManageLabel.setMaximumSize(new java.awt.Dimension(19, 196));

        jlabel26.setBackground(new java.awt.Color(204, 204, 204));
        jlabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel26.setText("THÔNG TIN");
        jlabel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel26MouseClicked(evt);
            }
        });

        findDocumentJLabel.setBackground(new java.awt.Color(204, 204, 204));
        findDocumentJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        findDocumentJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        findDocumentJLabel.setText("TÌM SÁCH");
        findDocumentJLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        findDocumentJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findDocumentJLabelMouseClicked(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("QUẢN LÝ NGƯỜI DÙNG");
        jLabel29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userNameManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(findDocumentJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(inFoManageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(inFoManageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameManage, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(findDocumentJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jlabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGE LIBRARY");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRANG QUẢN LÝ");

        jButton2.setForeground(new java.awt.Color(51, 102, 255));
        jButton2.setText("ĐĂNG XUẤT");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        titleJLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        titleJLabel5.setText("Sách gì đây ai biết 1");

        imageJLabel5.setBackground(new java.awt.Color(255, 0, 51));
        imageJLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BTL_OOP/image/Aram Khachaturyan.png"))); // NOI18N
        imageJLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageJLabel5MouseClicked(evt);
            }
        });

        titleJLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        titleJLabel1.setText("Sách gì đây ai biết 1");

        titleJLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        titleJLabel6.setText("Sách gì đây ai biết 1");

        imageJLabel1.setBackground(new java.awt.Color(255, 0, 51));
        imageJLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BTL_OOP/image/C++.png"))); // NOI18N
        imageJLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageJLabel1MouseClicked(evt);
            }
        });

        titleJLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        titleJLabel2.setText("Sách gì đây ai biết 1");

        imageJLabel2.setBackground(new java.awt.Color(255, 0, 51));
        imageJLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BTL_OOP/image/C_Programming.png"))); // NOI18N
        imageJLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageJLabel2MouseClicked(evt);
            }
        });

        titleJLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        titleJLabel3.setText("Sách gì đây ai biết 1");

        imageJLabel3.setBackground(new java.awt.Color(255, 0, 51));
        imageJLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BTL_OOP/image/C_Program_Design.png"))); // NOI18N
        imageJLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageJLabel3MouseClicked(evt);
            }
        });

        imageJLabel6.setBackground(new java.awt.Color(255, 0, 51));
        imageJLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BTL_OOP/image/An Inquiry Into the Nature and Causes of the Wealth of Nations.png"))); // NOI18N
        imageJLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageJLabel6MouseClicked(evt);
            }
        });

        titleJLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        titleJLabel4.setText("Sách gì đây ai biết 1");

        imageJLabel4.setBackground(new java.awt.Color(255, 0, 51));
        imageJLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BTL_OOP/image/C_For_Dummies_Volume_1.png"))); // NOI18N
        imageJLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageJLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout managePaneLayout = new javax.swing.GroupLayout(managePane);
        managePane.setLayout(managePaneLayout);
        managePaneLayout.setHorizontalGroup(
            managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePaneLayout.createSequentialGroup()
                .addGroup(managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managePaneLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(managePaneLayout.createSequentialGroup()
                                .addGroup(managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(imageJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(imageJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imageJLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleJLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(managePaneLayout.createSequentialGroup()
                                .addGroup(managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(imageJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(imageJLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleJLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imageJLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleJLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        managePaneLayout.setVerticalGroup(
            managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePaneLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managePaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(managePaneLayout.createSequentialGroup()
                                .addComponent(imageJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(managePaneLayout.createSequentialGroup()
                                .addComponent(imageJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(managePaneLayout.createSequentialGroup()
                                .addComponent(imageJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleJLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(managePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(managePaneLayout.createSequentialGroup()
                                .addComponent(imageJLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleJLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(managePaneLayout.createSequentialGroup()
                                .addComponent(imageJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(managePaneLayout.createSequentialGroup()
                                .addComponent(imageJLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleJLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))
                    .addGroup(managePaneLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managePane, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("managePanel");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        int result = JOptionPane.showConfirmDialog(
                null,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        
        if (result == JOptionPane.YES_OPTION) {
            CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
            cl.show(mainPanel, "loginPanel");
            LoginPanel.isManage = false;
            Map<JLabel, JLabel> labelMap = ManagePanel.getListRecomentDocumentJLabel();
            for (int i = 0; i < labelMap.size(); i++) {
                Map.Entry<JLabel, JLabel> entry = (Map.Entry<JLabel, JLabel>) labelMap.entrySet().toArray()[i];
                JLabel titleLabel = entry.getKey();
                JLabel imageLabel = entry.getValue();

                // Đặt lại tiêu đề và hình ảnh mặc định cho những JLabel còn lại
                titleLabel.setText("");  // Xóa tên tài liệu
                imageLabel.setIcon(null); // Xóa ảnh
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void findDocumentJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findDocumentJLabelMouseClicked

        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        cl.show(mainPanel, "findDocumentPanel");
        DisplayDocumentPanel.isFromHome = false;
        FindDocumentPanel.setUsername(getUsername());
    }//GEN-LAST:event_findDocumentJLabelMouseClicked

    private void jlabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel26MouseClicked

        InFoUserPanel.setDefaultInfo();
        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        InFoUserPanel.displayBorrowedDocument();
        cl.show(mainPanel, "inFoUserPanel");
    }//GEN-LAST:event_jlabel26MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        cl.show(mainPanel, "findBookManage");
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked

        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        cl.show(mainPanel, "manageDocumentPanel");
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked

        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        cl.show(mainPanel, "userManagementPanel");
        
    }//GEN-LAST:event_jLabel29MouseClicked

    private void imageJLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageJLabel5MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {  // Kiểm tra nếu người dùng nhấp đúp
            if (imageJLabel5.getIcon() != null) {
                render.renderDocumentToInfoDocument(imageJLabel5);
                CardLayout cl = (CardLayout) mainPanel.getLayout();
                cl.show(mainPanel, "displayDocumentPanel");
            }
        }
    }//GEN-LAST:event_imageJLabel5MouseClicked

    private void imageJLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageJLabel1MouseClicked
        if (evt.getClickCount() == 2) {  // Kiểm tra nếu người dùng nhấp đúp
            if (imageJLabel1.getIcon() != null) {
                render.renderDocumentToInfoDocument(imageJLabel1);
                CardLayout cl = (CardLayout) mainPanel.getLayout();
                cl.show(mainPanel, "displayDocumentPanel");
            }
        }
    }//GEN-LAST:event_imageJLabel1MouseClicked

    private void imageJLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageJLabel2MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {  // Kiểm tra nếu người dùng nhấp đúp
            if (imageJLabel2.getIcon() != null) {
                render.renderDocumentToInfoDocument(imageJLabel2);
                CardLayout cl = (CardLayout) mainPanel.getLayout();
                cl.show(mainPanel, "displayDocumentPanel");
            }
        }
    }//GEN-LAST:event_imageJLabel2MouseClicked

    private void imageJLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageJLabel3MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {  // Kiểm tra nếu người dùng nhấp đúp
            if (imageJLabel3.getIcon() != null) {
                render.renderDocumentToInfoDocument(imageJLabel3);
                CardLayout cl = (CardLayout) mainPanel.getLayout();
                cl.show(mainPanel, "displayDocumentPanel");
            }
        }
    }//GEN-LAST:event_imageJLabel3MouseClicked

    private void imageJLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageJLabel6MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {  // Kiểm tra nếu người dùng nhấp đúp
            if (imageJLabel6.getIcon() != null) {
                render.renderDocumentToInfoDocument(imageJLabel6);
                CardLayout cl = (CardLayout) mainPanel.getLayout();
                cl.show(mainPanel, "displayDocumentPanel");
            }
        }
    }//GEN-LAST:event_imageJLabel6MouseClicked

    private void imageJLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageJLabel4MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {  // Kiểm tra nếu người dùng nhấp đúp
            if (imageJLabel4.getIcon() != null) {
                render.renderDocumentToInfoDocument(imageJLabel4);
                CardLayout cl = (CardLayout) mainPanel.getLayout();
                cl.show(mainPanel, "displayDocumentPanel");
            }
        }
        
    }//GEN-LAST:event_imageJLabel4MouseClicked
    
    
    public static Map<JLabel, JLabel> getListRecomentDocumentJLabel() {
        Map<JLabel, JLabel> result = new LinkedHashMap<>();
        result.put(titleJLabel1, imageJLabel1);
        result.put(titleJLabel2, imageJLabel2);
        result.put(titleJLabel3, imageJLabel3);
        result.put(titleJLabel4, imageJLabel4);
        result.put(titleJLabel5, imageJLabel5);
        result.put(titleJLabel6, imageJLabel6);
        return result;
    }
    
    //Hiển thị sách gơij ý 
    public static void displayRecommentDocument() {
        // Lấy tất cả tài liệu từ cơ sở dữ liệu và lịch sử mượn trả
        ArrayList<Document> allDocument = DocumentDAO.getAllDocuments();
        TransactionDAO transaction = new TransactionDAO();
        ArrayList<Document> suggest = transaction.topDocument(LoginPanel.userOverAll);
        
        // Lấy Map chứa các JLabel cho tiêu đề và ảnh
        Map<JLabel, JLabel> labelMap = getListRecomentDocumentJLabel();
        
        render.renderDocument(suggest, labelMap);
    }
    
    public static void setUsername(String username){
        ManagePanel.userNameManage.setText(username);
    }

    public static String getUsername() {
        return userNameManage.getText();
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel findDocumentJLabel;
    private javax.swing.JLabel home;
    private static javax.swing.JLabel imageJLabel1;
    private static javax.swing.JLabel imageJLabel2;
    private static javax.swing.JLabel imageJLabel3;
    private static javax.swing.JLabel imageJLabel4;
    private static javax.swing.JLabel imageJLabel5;
    private static javax.swing.JLabel imageJLabel6;
    private javax.swing.JLabel inFoManageLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jlabel26;
    private javax.swing.JPanel managePane;
    private static javax.swing.JLabel titleJLabel1;
    private static javax.swing.JLabel titleJLabel2;
    private static javax.swing.JLabel titleJLabel3;
    private static javax.swing.JLabel titleJLabel4;
    private static javax.swing.JLabel titleJLabel5;
    private static javax.swing.JLabel titleJLabel6;
    private static javax.swing.JLabel userNameManage;
    // End of variables declaration//GEN-END:variables
}
