/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BTL_OOP.main.ui.manage;

import BTL_OOP.main.ui.login.LoginPanel;
import BTL_OOP.main.models.user.User;
import BTL_OOP.main.dao.DocumentDAO;
import BTL_OOP.main.models.document.Book;
import BTL_OOP.main.models.document.Document;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ManageDocumentPanel extends javax.swing.JPanel {

    
    private Connection con;
    JFrame frame;
    JPanel mainPanel;
    static User user;
    private static int rowNow ;
    
    public static List<Document> arrDocument = DocumentDAO.getAllDocuments();
    
    public ManageDocumentPanel() {
        initComponents();
        setTable();
    }
    
    public ManageDocumentPanel(Connection con, JFrame frame, JPanel mainPanel) {
        initComponents();
        this.con = con;
        this.frame = frame;
        this.mainPanel = mainPanel;
        if(user == null) {
            user = new User();
        }
        setTable();
        
    }
    /**
     * Thêm menu.
     */
        public void addMenuItem() {
        manageMenu.setBackground(new Color(50, 50, 50));  // Màu nền cho menu
        manageMenu.setForeground(Color.WHITE);            // Màu chữ cho menu

        trangchu.setBackground(new Color(255, 255, 255));       // Màu nền cho item
        trangchu.setForeground(Color.BLACK);                 // Màu chữ cho item
        themSach.setBackground(new Color(255, 255, 255));       // Màu nền cho item
        themSach.setForeground(Color.BLACK);                 // Màu chữ cho item
        timsach.setBackground(new Color(255, 255, 255));
        timsach.setForeground(Color.BLACK);
        thongtin.setBackground(new Color(255, 255, 255));
        thongtin.setForeground(Color.BLACK);
        nguoidung.setBackground(new Color(255, 255, 255));
        nguoidung.setForeground(Color.BLACK);
        
        manageMenu.add(trangchu);
        manageMenu.add(themSach);
        manageMenu.add(timsach);
        manageMenu.add(nguoidung);
    }

        /**
         * Load thông tin từ api lên bảng bảng.
         */
    public void setTable() {
        arrDocument = DocumentDAO.getAllDocuments();
        String[] colums = {"ID", "Tên tài liệu", "Tác giả", "Nhà xuất bản", 
            "Ngày xuất bản", "Số lượng", "Ngôn ngữ", "Thể loại", "Mô tả" };
        DefaultTableModel tableModel = new DefaultTableModel(colums, 0);
        tableModel.setRowCount(0);
        
        for (Document x : arrDocument) {
            tableModel.addRow(new Object[] {
                x.getID(),
                x.getTitle(),
                x.getAuthor(),
                x.getPublisher(),
                x.getPublishedDate(),
                x.getQuantity(),
                x.getLanguage(),
                x.getCategory(),
                x.getDescription()
            });
        }
        infoDocument.setModel(tableModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        manageMenu = new javax.swing.JPopupMenu();
        trangchu = new javax.swing.JMenuItem();
        themSach = new javax.swing.JMenuItem();
        timsach = new javax.swing.JMenuItem();
        thongtin = new javax.swing.JMenuItem();
        nguoidung = new javax.swing.JMenuItem();
        removeDialog = new javax.swing.JDialog();
        questionDiaLog = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        nameDialog = new javax.swing.JLabel();
        authorDialog = new javax.swing.JLabel();
        publisherDialog = new javax.swing.JLabel();
        publishedDateDialog = new javax.swing.JLabel();
        quantityDialog = new javax.swing.JLabel();
        title5 = new javax.swing.JLabel();
        categoryDialog = new javax.swing.JLabel();
        confirmRemove = new javax.swing.JButton();
        cancelRemove = new javax.swing.JButton();
        editDialog = new javax.swing.JDialog();
        questionDiaLog1 = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        title7 = new javax.swing.JLabel();
        title8 = new javax.swing.JLabel();
        confirmEdit = new javax.swing.JButton();
        title9 = new javax.swing.JLabel();
        cancelEdit = new javax.swing.JButton();
        title10 = new javax.swing.JLabel();
        title11 = new javax.swing.JLabel();
        nameDialog1 = new javax.swing.JTextField();
        authorDialog1 = new javax.swing.JTextField();
        publisherDialog1 = new javax.swing.JTextField();
        publishedDateDialog1 = new javax.swing.JTextField();
        quantityDialog1 = new javax.swing.JTextField();
        categoryDialog1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoDocument = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        refresh = new javax.swing.JButton();

        trangchu.setText("Trang chủ");
        trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trangchuActionPerformed(evt);
            }
        });
        manageMenu.add(trangchu);

        themSach.setText("Thêm sách");
        themSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSachActionPerformed(evt);
            }
        });
        manageMenu.add(themSach);

        timsach.setText("Tìm sách");
        timsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timsachActionPerformed(evt);
            }
        });
        manageMenu.add(timsach);

        thongtin.setText("Thông tin");
        thongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongtinActionPerformed(evt);
            }
        });
        manageMenu.add(thongtin);

        nguoidung.setText("Người dùng");
        manageMenu.add(nguoidung);

        removeDialog.setSize(new java.awt.Dimension(500, 350));

        questionDiaLog.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        questionDiaLog.setText("Bạn muốn xoá tài liệu ?");

        title.setText("Tên tài liệu:");

        title1.setText("Tác giả:");

        title2.setText("Nhà xuất bản:");

        title3.setText("Số lượng:");

        title4.setText("Ngày xuất bản:");

        nameDialog.setText("jLabel28");

        authorDialog.setText("jLabel28");

        publisherDialog.setText("jLabel28");

        publishedDateDialog.setText("jLabel28");

        quantityDialog.setText("jLabel28");

        title5.setText("Thể loại:");

        categoryDialog.setText("jLabel28");

        confirmRemove.setBackground(new java.awt.Color(255, 51, 102));
        confirmRemove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmRemove.setText("Xoá");
        confirmRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRemoveActionPerformed(evt);
            }
        });

        cancelRemove.setBackground(new java.awt.Color(51, 153, 255));
        cancelRemove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelRemove.setText("Huỷ");
        cancelRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelRemoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout removeDialogLayout = new javax.swing.GroupLayout(removeDialog.getContentPane());
        removeDialog.getContentPane().setLayout(removeDialogLayout);
        removeDialogLayout.setHorizontalGroup(
            removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeDialogLayout.createSequentialGroup()
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeDialogLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(questionDiaLog))
                    .addGroup(removeDialogLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title)
                            .addComponent(title1)
                            .addComponent(title2)
                            .addComponent(title4)
                            .addComponent(title3)
                            .addComponent(title5))
                        .addGap(28, 28, 28)
                        .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publishedDateDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publisherDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(removeDialogLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(confirmRemove)
                        .addGap(18, 18, 18)
                        .addComponent(cancelRemove)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        removeDialogLayout.setVerticalGroup(
            removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeDialogLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(questionDiaLog, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(nameDialog))
                .addGap(10, 10, 10)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title1)
                    .addComponent(authorDialog))
                .addGap(10, 10, 10)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title2)
                    .addComponent(publisherDialog))
                .addGap(10, 10, 10)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title4)
                    .addComponent(publishedDateDialog))
                .addGap(10, 10, 10)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title3)
                    .addComponent(quantityDialog))
                .addGap(10, 10, 10)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title5)
                    .addComponent(categoryDialog))
                .addGap(18, 18, 18)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmRemove)
                    .addComponent(cancelRemove))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editDialog.setSize(new java.awt.Dimension(500, 350));

        questionDiaLog1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        questionDiaLog1.setText("Bạn muốn sửa tài liệu ?");

        title6.setText("Thể loại:");

        title7.setText("Tên tài liệu:");

        title8.setText("Tác giả:");

        confirmEdit.setBackground(new java.awt.Color(255, 51, 102));
        confirmEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmEdit.setText("Sửa");
        confirmEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmEditActionPerformed(evt);
            }
        });

        title9.setText("Nhà xuất bản:");

        cancelEdit.setBackground(new java.awt.Color(51, 153, 255));
        cancelEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelEdit.setText("Huỷ");
        cancelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelEditMouseClicked(evt);
            }
        });

        title10.setText("Số lượng:");

        title11.setText("Ngày xuất bản:");

        nameDialog1.setText("jTextField1");

        authorDialog1.setText("jTextField1");

        publisherDialog1.setText("jTextField1");

        publishedDateDialog1.setText("jTextField1");

        quantityDialog1.setText("jTextField1");

        categoryDialog1.setText("jTextField1");

        javax.swing.GroupLayout editDialogLayout = new javax.swing.GroupLayout(editDialog.getContentPane());
        editDialog.getContentPane().setLayout(editDialogLayout);
        editDialogLayout.setHorizontalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(questionDiaLog1))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editDialogLayout.createSequentialGroup()
                                .addComponent(title7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editDialogLayout.createSequentialGroup()
                                .addComponent(title8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(authorDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editDialogLayout.createSequentialGroup()
                                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editDialogLayout.createSequentialGroup()
                                        .addComponent(title9)
                                        .addGap(18, 18, 18)
                                        .addComponent(publisherDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(editDialogLayout.createSequentialGroup()
                                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(title11)
                                            .addComponent(title10)
                                            .addComponent(title6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(categoryDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(quantityDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(publishedDateDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(confirmEdit)
                        .addGap(18, 18, 18)
                        .addComponent(cancelEdit)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        editDialogLayout.setVerticalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(questionDiaLog1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title7)
                    .addComponent(nameDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title8)
                    .addComponent(authorDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title9)
                    .addComponent(publisherDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title11)
                    .addComponent(publishedDateDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title10)
                    .addComponent(quantityDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title6)
                    .addComponent(categoryDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmEdit)
                    .addComponent(cancelEdit))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 45));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("MANAGE LIBRARY");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("TRANG QUẢN LÝ");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel27MouseEntered(evt);
            }
        });

        jButton14.setForeground(new java.awt.Color(51, 102, 255));
        jButton14.setText("ĐĂNG XUẤT");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel14.setBackground(new java.awt.Color(244, 244, 244));
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý tài liệu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 126, 0, 0);
        jPanel14.add(jLabel1, gridBagConstraints);

        infoDocument.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên tài liệu", "Tác giả", "Nhà xuất bản", "Ngày xuất bản", "Số lượng", "Ngôn ngữ", "Thể loại", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        infoDocument.setRowHeight(30);
        infoDocument.setShowGrid(false);
        jScrollPane1.setViewportView(infoDocument);
        if (infoDocument.getColumnModel().getColumnCount() > 0) {
            infoDocument.getColumnModel().getColumn(0).setPreferredWidth(40);
            infoDocument.getColumnModel().getColumn(1).setPreferredWidth(150);
            infoDocument.getColumnModel().getColumn(2).setPreferredWidth(120);
            infoDocument.getColumnModel().getColumn(3).setPreferredWidth(120);
            infoDocument.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel15);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 778;
        gridBagConstraints.ipady = 422;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 6);
        jPanel14.add(jScrollPane2, gridBagConstraints);

        edit.setBackground(new java.awt.Color(0, 153, 255));
        edit.setText("Sửa");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 18, 0, 0);
        jPanel14.add(edit, gridBagConstraints);

        remove.setBackground(new java.awt.Color(255, 51, 51));
        remove.setText("Xoá");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 6, 0, 0);
        jPanel14.add(remove, gridBagConstraints);

        refresh.setBackground(new java.awt.Color(227, 222, 222));
        refresh.setText("Cập nhật");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 214, 0, 6);
        jPanel14.add(refresh, gridBagConstraints);

        add(jPanel14, java.awt.BorderLayout.CENTER);
        jPanel14.getAccessibleContext().setAccessibleName("manageDocumentPanel");

        getAccessibleContext().setAccessibleName("manageDocumentPanel");
    }// </editor-fold>//GEN-END:initComponents
    /** 
     * Confirm đằn xuất là reset dữ liệu.
     * @param evt 
     */
    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        int choose = JOptionPane.showConfirmDialog(
            mainPanel, 
            "Bạn muốn đăng xuất?", 
            "Xác nhận đăng xuất", 
            JOptionPane.YES_NO_OPTION
        );

        if (choose == JOptionPane.YES_OPTION) {
            
            CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
            cl.show(mainPanel, "loginPanel"); // Chuyển sang panel "loginPanel"
            LoginPanel.isManage = false;

            Map<JLabel, JLabel> labelMap = ManagePanel.getListRecomentDocumentJLabel();
            for (int i = 0; i < labelMap.size(); i++) {
                Map.Entry<JLabel, JLabel> entry = (Map.Entry<JLabel, JLabel>) labelMap.entrySet().toArray()[i];
                JLabel titleLabel = entry.getKey();
                JLabel imageLabel = entry.getValue();

                // Đặt lại tiêu đề và hình ảnh mặc định cho những JLabel còn lại
                titleLabel.setText("");  // Xóa tên tài liệu
                imageLabel.setIcon(null); // Xóa ảnh
            }
        }

    }//GEN-LAST:event_jButton14MouseClicked
    
    /**
     * Chuyển sang trang chủ quản lý.
     * @param evt mouseclick
     */
    private void trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trangchuActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        cl.show(mainPanel, "managePanel");
    }//GEN-LAST:event_trangchuActionPerformed
    
    /**
     * Chuyển sang trang tìm kiếm.
     * @param evt mouseclick
     */
    private void timsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timsachActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        cl.show(mainPanel, "findDocumentPanel");
    }//GEN-LAST:event_timsachActionPerformed

    
    private void thongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongtinActionPerformed

    }//GEN-LAST:event_thongtinActionPerformed

    /**
     * Load lại dữ liệu trên bảng.
     * @param evt 
     */
    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        setTable();
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * Nhấn nút xác nhận xoá.
     * thực hiện xoá
     * @param evt 
     */
    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        int selectedRow = infoDocument.getSelectedRow();

        rowNow = selectedRow;
        if (selectedRow != -1) {
            // Lấy dữ liệu từ các cột
            Object id = infoDocument.getValueAt(selectedRow, 0);
            Object title = infoDocument.getValueAt(selectedRow, 1);
            Object author = infoDocument.getValueAt(selectedRow, 2);
            Object publisher = infoDocument.getValueAt(selectedRow, 3);
            Object publishedDate = infoDocument.getValueAt(selectedRow, 4);
            Object quantity = infoDocument.getValueAt(selectedRow, 5);
            Object language = infoDocument.getValueAt(selectedRow, 6);
            Object category = infoDocument.getValueAt(selectedRow, 7);
            Object description = infoDocument.getValueAt(selectedRow, 8);

            // Cập nhật nội dung vào các ô dialog
            nameDialog.setText(title != null ? title.toString() : "");
            authorDialog.setText(author != null ? author.toString() : "");
            publisherDialog.setText(publisher != null ? publisher.toString() : "");
            publishedDateDialog.setText(publishedDate != null ? publishedDate.toString() : "");
            quantityDialog.setText(quantity != null ? quantity.toString() : "");
            categoryDialog.setText(category != null ? category.toString() : "");
        } else {
            JOptionPane.showMessageDialog(frame, "Vui lòng chọn một hàng trước khi xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Hiển thị dialog
        removeDialog.setLocationRelativeTo(frame);
        removeDialog.setVisible(true);
    }//GEN-LAST:event_removeActionPerformed

    private void confirmRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmRemoveActionPerformed
        DocumentDAO dc = new DocumentDAO();
        Object b = infoDocument.getValueAt(rowNow, 0);
        dc.removeDocument(Integer.parseInt(b.toString()));
        System.out.println(Integer.parseInt(b.toString()));
        setTable();
        removeDialog.setVisible(false);
    }//GEN-LAST:event_confirmRemoveActionPerformed

    private void jLabel27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseEntered
        manageMenu.show(jLabel27, evt.getX(), evt.getY());
    }//GEN-LAST:event_jLabel27MouseEntered

    /**
     * Nhấn nút huỷ thì đóng dialog.
     * @param evt mouseclick
     */
    private void cancelRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelRemoveMouseClicked
        removeDialog.setVisible(false);
    }//GEN-LAST:event_cancelRemoveMouseClicked

    /**
     * Đi đến trang tìm kiếm khi cần thêm sách.
     * @param evt 
     */
    private void themSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themSachActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        cl.show(mainPanel, "findBookManage");
    }//GEN-LAST:event_themSachActionPerformed

    /**
     * Load thông tin lên dialog.
     * @param evt mouseClick
     */
    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        int selectedRow = infoDocument.getSelectedRow();

        rowNow = selectedRow;
        if (selectedRow != -1) {
            // Lấy dữ liệu từ các cột
            Object id = infoDocument.getValueAt(selectedRow, 0);
            Object title = infoDocument.getValueAt(selectedRow, 1);
            Object author = infoDocument.getValueAt(selectedRow, 2);
            Object publisher = infoDocument.getValueAt(selectedRow, 3);
            Object publishedDate = infoDocument.getValueAt(selectedRow, 4);
            Object quantity = infoDocument.getValueAt(selectedRow, 5);
            Object language = infoDocument.getValueAt(selectedRow, 6);
            Object category = infoDocument.getValueAt(selectedRow, 7);
            Object description = infoDocument.getValueAt(selectedRow, 8);

            // Cập nhật nội dung vào các ô dialog
            nameDialog1.setText(title != null ? title.toString() : "");
            authorDialog1.setText(author != null ? author.toString() : "");
            publisherDialog1.setText(publisher != null ? publisher.toString() : "");
            publishedDateDialog1.setText(publishedDate != null ? publishedDate.toString() : "");
            quantityDialog1.setText(quantity != null ? quantity.toString() : "");
            categoryDialog1.setText(category != null ? category.toString() : "");
        } else {
            JOptionPane.showMessageDialog(frame, "Vui lòng chọn một hàng trước khi sửa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Hiển thị dialog
        editDialog.setLocationRelativeTo(frame);
        editDialog.setVisible(true);
    }//GEN-LAST:event_editActionPerformed

    /**
     * Nhấn nút xác nhận sửa thì thực hiện kiểm tra thông tin và sửa.
     * @param evt mouseClick
     */
    private void confirmEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmEditActionPerformed
            Book Abook = new Book();
            Abook.setID((Integer) infoDocument.getValueAt(rowNow, 0));
            Abook.setTitle(nameDialog1.getText());
            Abook.setAuthor(authorDialog1.getText());
            Abook.setPublisher(publisherDialog1.getText());
            Abook.setPublishedDate(publishedDateDialog1.getText());
            Abook.setQuantity(Integer.parseInt(quantityDialog1.getText()));
            Abook.setCategory(categoryDialog1.getText());
            Abook.setDescription(infoDocument.getValueAt(rowNow, 8).toString());
            Abook.setLanguage(infoDocument.getValueAt(rowNow, 6).toString());
            
            DocumentDAO dc = new DocumentDAO();
            dc.updateDocument(Abook);
            setTable();
            editDialog.setVisible(false);
            
            
    }//GEN-LAST:event_confirmEditActionPerformed

    /**
     * Huỷ thì đóng dialog.
     * @param evt 
     */
    private void cancelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelEditMouseClicked
        editDialog.setVisible(false);
    }//GEN-LAST:event_cancelEditMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorDialog;
    private javax.swing.JTextField authorDialog1;
    private javax.swing.JButton cancelEdit;
    private javax.swing.JButton cancelRemove;
    private javax.swing.JLabel categoryDialog;
    private javax.swing.JTextField categoryDialog1;
    private javax.swing.JButton confirmEdit;
    private javax.swing.JButton confirmRemove;
    private javax.swing.JButton edit;
    private javax.swing.JDialog editDialog;
    private javax.swing.JTable infoDocument;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu manageMenu;
    private javax.swing.JLabel nameDialog;
    private javax.swing.JTextField nameDialog1;
    private javax.swing.JMenuItem nguoidung;
    private javax.swing.JLabel publishedDateDialog;
    private javax.swing.JTextField publishedDateDialog1;
    private javax.swing.JLabel publisherDialog;
    private javax.swing.JTextField publisherDialog1;
    private javax.swing.JLabel quantityDialog;
    private javax.swing.JTextField quantityDialog1;
    private javax.swing.JLabel questionDiaLog;
    private javax.swing.JLabel questionDiaLog1;
    private javax.swing.JButton refresh;
    private javax.swing.JButton remove;
    private javax.swing.JDialog removeDialog;
    private javax.swing.JMenuItem themSach;
    private javax.swing.JMenuItem thongtin;
    private javax.swing.JMenuItem timsach;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title10;
    private javax.swing.JLabel title11;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    private javax.swing.JMenuItem trangchu;
    // End of variables declaration//GEN-END:variables
}
