/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BTL_OOP.main.ui.manage;

import BTL_OOP.main.Main;
import BTL_OOP.main.dao.ManageDAO;
import BTL_OOP.main.ui.login.LoginPanel;
import BTL_OOP.main.models.user.User;
import BTL_OOP.main.ui.users.UserPanel;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import BTL_OOP.main.services.CheckInput;
import BTL_OOP.main.ui.users.UserPanel;
import java.awt.CardLayout;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thinh
 */
public class UserManagementPanel extends javax.swing.JPanel {
    
    private final JFrame mainFrame;
    JPanel mainPanel;
    static User user;
    private static int rowNow ;
    ManageDAO manageDao = ManageDAO.getManageDAO();
    /**
     * Creates new form UserManagementPanel
     */
    public UserManagementPanel() {
        initComponents();  
        this.mainPanel = Main.mainPanel;
        this.mainFrame = Main.mainFrame;
        if(user == null) {
            user = new User();
        }
        loadUserTable();
    }
    
    
    /**
     * Tải thông tin người dùng lên bảng.
     * Lấy thông tin từ cơ sở dữ liệu và sửa.
     */
    public void loadUserTable() {
    // Định nghĩa các cột hiển thị
        String[] columns = {"ID", "Họ và tên", "Tài khoản", "Mật khẩu" ,"Email", "SĐT", "Ngày sinh", "Địa chỉ", "Số sách mượn"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        // Xóa dữ liệu cũ
        model.setRowCount(0);  
         
        // Lấy danh sách người dùng từ lớp quản lý
        ArrayList<User> users = manageDao.getAllUsers();

        for (User x: users) {
            System.out.println(x.getID());
        }
        
        if (users == null || users.isEmpty()) {
            // Nếu danh sách người dùng rỗng, hiển thị thông báo
            System.out.println("Không có dữ liệu người dùng để hiển thị.");
            return;
        }

        // Đổ dữ liệu từ danh sách vào bảng
        for (User user : users) {
            model.addRow(new Object[]{
                user.getID(),
                user.getName(),
                user.getUsername(),
                user.getPassword(),
                user.getEmail(),
                user.getPhone(),
                user.getBirthday(),
                user.getAddress(),
                user.getNumberBorrowed()
            });
        }

        // Gán mô hình mới cho bảng
        infoUser.setModel(model);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageMenu = new javax.swing.JPopupMenu();
        trangchu = new javax.swing.JMenuItem();
        themSach = new javax.swing.JMenuItem();
        quanLySach = new javax.swing.JMenuItem();
        timsach = new javax.swing.JMenuItem();
        thongtin = new javax.swing.JMenuItem();
        removeDialog = new javax.swing.JDialog();
        questionDiaLog = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        nameDialog = new javax.swing.JLabel();
        emailDialog = new javax.swing.JLabel();
        phoneDialog = new javax.swing.JLabel();
        birthdayDialog = new javax.swing.JLabel();
        adressDialog = new javax.swing.JLabel();
        title5 = new javax.swing.JLabel();
        totalDialog = new javax.swing.JLabel();
        confirmRemove = new javax.swing.JButton();
        cancelRemove = new javax.swing.JButton();
        editDialog = new javax.swing.JDialog();
        questionDiaLog1 = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        confirmEdit = new javax.swing.JButton();
        email = new javax.swing.JLabel();
        cancelEdit = new javax.swing.JButton();
        title10 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        nameDialog1 = new javax.swing.JTextField();
        passDialog1 = new javax.swing.JTextField();
        emailDialog1 = new javax.swing.JTextField();
        phoneDialog1 = new javax.swing.JTextField();
        addressDialog1 = new javax.swing.JTextField();
        birtDialog1 = new javax.swing.JTextField();
        title12 = new javax.swing.JLabel();
        totalDialog1 = new javax.swing.JTextField();
        addDialog1 = new javax.swing.JDialog();
        questionDiaLog2 = new javax.swing.JLabel();
        title7 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        pass1 = new javax.swing.JLabel();
        confirmEdit1 = new javax.swing.JButton();
        email1 = new javax.swing.JLabel();
        cancelEdit1 = new javax.swing.JButton();
        title11 = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        passDialog2 = new javax.swing.JTextField();
        emailDialog2 = new javax.swing.JTextField();
        phoneDialog2 = new javax.swing.JTextField();
        addressDialog2 = new javax.swing.JTextField();
        birtDialog2 = new javax.swing.JTextField();
        title13 = new javax.swing.JLabel();
        totalDialog2 = new javax.swing.JTextField();
        title14 = new javax.swing.JLabel();
        accountDialog2 = new javax.swing.JTextField();
        nameDialog2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoUser = new javax.swing.JTable();
        addUserbutton = new javax.swing.JButton();
        editUserButton = new javax.swing.JButton();
        removeUserButton = new javax.swing.JButton();
        refreshUserButton = new javax.swing.JButton();

        trangchu.setText("Trang chủ");
        trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trangchuActionPerformed(evt);
            }
        });
        manageMenu.add(trangchu);

        themSach.setText("Thêm sách");
        themSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSachActionPerformed(evt);
            }
        });
        manageMenu.add(themSach);

        quanLySach.setText("Quản lý tài liệu");
        quanLySach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLySachActionPerformed(evt);
            }
        });
        manageMenu.add(quanLySach);

        timsach.setText("Tìm sách");
        timsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timsachActionPerformed(evt);
            }
        });
        manageMenu.add(timsach);

        thongtin.setText("Thông tin");
        thongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongtinActionPerformed(evt);
            }
        });
        manageMenu.add(thongtin);

        removeDialog.setSize(new java.awt.Dimension(500, 350));

        questionDiaLog.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        questionDiaLog.setText("Bạn muốn xoá tài liệu ?");

        title.setText("Họ và tên:");

        title1.setText("Email:");

        title2.setText("SĐT:");

        title3.setText("Địa chỉ:");

        title4.setText("Ngày sinh:");

        nameDialog.setText("jLabel28");

        emailDialog.setText("jLabel28");

        phoneDialog.setText("jLabel28");

        birthdayDialog.setText("jLabel28");

        adressDialog.setText("jLabel28");

        title5.setText("Sách mượn:");

        totalDialog.setText("jLabel28");

        confirmRemove.setBackground(new java.awt.Color(255, 51, 102));
        confirmRemove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmRemove.setText("Xoá");
        confirmRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRemoveActionPerformed(evt);
            }
        });

        cancelRemove.setBackground(new java.awt.Color(51, 153, 255));
        cancelRemove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelRemove.setText("Huỷ");
        cancelRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelRemoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout removeDialogLayout = new javax.swing.GroupLayout(removeDialog.getContentPane());
        removeDialog.getContentPane().setLayout(removeDialogLayout);
        removeDialogLayout.setHorizontalGroup(
            removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeDialogLayout.createSequentialGroup()
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeDialogLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(questionDiaLog))
                    .addGroup(removeDialogLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title)
                            .addComponent(title1)
                            .addComponent(title2)
                            .addComponent(title4)
                            .addComponent(title3)
                            .addComponent(title5))
                        .addGap(28, 28, 28)
                        .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adressDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthdayDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(removeDialogLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(confirmRemove)
                        .addGap(18, 18, 18)
                        .addComponent(cancelRemove)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        removeDialogLayout.setVerticalGroup(
            removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeDialogLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(questionDiaLog, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(nameDialog))
                .addGap(10, 10, 10)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title1)
                    .addComponent(emailDialog))
                .addGap(10, 10, 10)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title2)
                    .addComponent(phoneDialog))
                .addGap(10, 10, 10)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title4)
                    .addComponent(birthdayDialog))
                .addGap(10, 10, 10)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title3)
                    .addComponent(adressDialog))
                .addGap(10, 10, 10)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title5)
                    .addComponent(totalDialog))
                .addGap(18, 18, 18)
                .addGroup(removeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmRemove)
                    .addComponent(cancelRemove))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editDialog.setSize(new java.awt.Dimension(500, 350));

        questionDiaLog1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        questionDiaLog1.setText("Sửa thông tin người dùng");

        title6.setText("Ngày sinh:");

        name.setText("Họ và tên:");

        pass.setText("Mật khẩu:");

        confirmEdit.setBackground(new java.awt.Color(255, 51, 102));
        confirmEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmEdit.setText("Sửa");
        confirmEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmEditActionPerformed(evt);
            }
        });

        email.setText("Email:");

        cancelEdit.setBackground(new java.awt.Color(51, 153, 255));
        cancelEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelEdit.setText("Huỷ");
        cancelEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelEditMouseClicked(evt);
            }
        });
        cancelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditActionPerformed(evt);
            }
        });

        title10.setText("Địa chỉ:");

        phone.setText("SĐT:              ");

        nameDialog1.setToolTipText("Nhập tên");
        nameDialog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameDialog1ActionPerformed(evt);
            }
        });

        passDialog1.setToolTipText("Nhập mật khẩu");

        emailDialog1.setToolTipText("nhập email");

        phoneDialog1.setToolTipText("Nhập số điện thoại");

        addressDialog1.setToolTipText("nhập địa chỉ");

        title12.setText("Số sách mượn:");

        javax.swing.GroupLayout editDialogLayout = new javax.swing.GroupLayout(editDialog.getContentPane());
        editDialog.getContentPane().setLayout(editDialogLayout);
        editDialogLayout.setHorizontalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(questionDiaLog1))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone)
                            .addComponent(title10)
                            .addComponent(title6)
                            .addComponent(email)
                            .addComponent(name)
                            .addComponent(pass)
                            .addComponent(title12))
                        .addGap(21, 21, 21)
                        .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birtDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editDialogLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(confirmEdit)
                        .addGap(18, 18, 18)
                        .addComponent(cancelEdit)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        editDialogLayout.setVerticalGroup(
            editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDialogLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(questionDiaLog1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(nameDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass)
                    .addComponent(passDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(phoneDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title10)
                    .addComponent(addressDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title6)
                    .addComponent(birtDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title12)
                    .addComponent(totalDialog1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(editDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmEdit)
                    .addComponent(cancelEdit))
                .addGap(17, 17, 17))
        );

        addDialog1.setSize(new java.awt.Dimension(500, 400));

        questionDiaLog2.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        questionDiaLog2.setText("Thêm người dùng ?");

        title7.setText("Ngày sinh:");

        name1.setText("Họ và tên:");

        pass1.setText("Mật khẩu:");

        confirmEdit1.setBackground(new java.awt.Color(255, 51, 102));
        confirmEdit1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmEdit1.setText("Thêm");
        confirmEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmEdit1ActionPerformed(evt);
            }
        });

        email1.setText("Email:");

        cancelEdit1.setBackground(new java.awt.Color(51, 153, 255));
        cancelEdit1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelEdit1.setText("Huỷ");
        cancelEdit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelEdit1MouseClicked(evt);
            }
        });
        cancelEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEdit1ActionPerformed(evt);
            }
        });

        title11.setText("Địa chỉ:");

        phone1.setText("SĐT:              ");

        title13.setText("Số sách mượn:");

        title14.setText("Tài khoản:");

        nameDialog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameDialog2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDialog1Layout = new javax.swing.GroupLayout(addDialog1.getContentPane());
        addDialog1.getContentPane().setLayout(addDialog1Layout);
        addDialog1Layout.setHorizontalGroup(
            addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialog1Layout.createSequentialGroup()
                .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDialog1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phone1)
                            .addComponent(title11)
                            .addComponent(title7)
                            .addComponent(email1)
                            .addComponent(name1)
                            .addComponent(pass1)
                            .addComponent(title13)
                            .addComponent(title14))
                        .addGap(21, 21, 21)
                        .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birtDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(questionDiaLog2)
                            .addComponent(accountDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addDialog1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(confirmEdit1)
                        .addGap(18, 18, 18)
                        .addComponent(cancelEdit1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addDialog1Layout.setVerticalGroup(
            addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialog1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(questionDiaLog2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1)
                    .addComponent(nameDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass1)
                    .addComponent(passDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email1)
                    .addComponent(emailDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone1)
                    .addComponent(phoneDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title11)
                    .addComponent(addressDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title7)
                    .addComponent(birtDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title13)
                    .addComponent(totalDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title14)
                    .addComponent(accountDialog2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmEdit1)
                    .addComponent(cancelEdit1))
                .addGap(17, 17, 17))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 650));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 40));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("MANAGE LIBRARY");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("TRANG QUẢN LÝ");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel27MouseEntered(evt);
            }
        });

        jButton14.setForeground(new java.awt.Color(51, 102, 255));
        jButton14.setText("ĐĂNG XUẤT");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jButton14))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(244, 244, 244));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý người dùng");

        infoUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ và tên", "Tài khoản", "Mật khẩu", "Email", "SĐT", "Ngày Sinh", "Địa chỉ", "Số sách mượn"
            }
        ));
        infoUser.setRowHeight(30);
        jScrollPane2.setViewportView(infoUser);
        if (infoUser.getColumnModel().getColumnCount() > 0) {
            infoUser.getColumnModel().getColumn(0).setPreferredWidth(40);
            infoUser.getColumnModel().getColumn(1).setPreferredWidth(100);
            infoUser.getColumnModel().getColumn(8).setPreferredWidth(40);
        }

        javax.swing.GroupLayout infoTableLayout = new javax.swing.GroupLayout(infoTable);
        infoTable.setLayout(infoTableLayout);
        infoTableLayout.setHorizontalGroup(
            infoTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoTableLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        infoTableLayout.setVerticalGroup(
            infoTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoTableLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(infoTable);

        addUserbutton.setBackground(new java.awt.Color(0, 102, 255));
        addUserbutton.setText("Thêm");
        addUserbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserbuttonActionPerformed(evt);
            }
        });

        editUserButton.setBackground(new java.awt.Color(180, 255, 156));
        editUserButton.setText("Sửa");
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });

        removeUserButton.setBackground(new java.awt.Color(255, 51, 51));
        removeUserButton.setText("Xoá");
        removeUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUserButtonActionPerformed(evt);
            }
        });

        refreshUserButton.setBackground(new java.awt.Color(234, 234, 234));
        refreshUserButton.setText("cập nhật");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 260, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addUserbutton)
                        .addGap(18, 18, 18)
                        .addComponent(editUserButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshUserButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserbutton)
                    .addComponent(editUserButton)
                    .addComponent(removeUserButton)
                    .addComponent(refreshUserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Hiển thị menu.
     * @param evt 
     */
    private void jLabel27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseEntered
        manageMenu.show(jLabel27, evt.getX(), evt.getY());
    }//GEN-LAST:event_jLabel27MouseEntered

    /**
     * Hiển thị thông báo confirm logout.
     * @param evt 
     */
    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        int result = JOptionPane.showConfirmDialog(
                null,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        
        if (result == JOptionPane.YES_OPTION) {
            CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
            cl.show(mainPanel, "loginPanel");
            LoginPanel.isManage = false;
            Map<JLabel, JLabel> labelMap = UserPanel.getListRecomentDocumentJLabel();
            for (int i = 0; i < labelMap.size(); i++) {
                Map.Entry<JLabel, JLabel> entry = (Map.Entry<JLabel, JLabel>) labelMap.entrySet().toArray()[i];
                JLabel titleLabel = entry.getKey();
                JLabel imageLabel = entry.getValue();

                // Đặt lại tiêu đề và hình ảnh mặc định cho những JLabel còn lại
                titleLabel.setText("");  // Xóa tên tài liệu
                imageLabel.setIcon(null); // Xóa ảnh
            }
        }
    }//GEN-LAST:event_jButton14MouseClicked

    /**
     * Chuyển trang.
     * @param evt 
     */
    private void trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trangchuActionPerformed
        System.out.println(mainPanel);
        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        cl.show(mainPanel, "managePanel");
    }//GEN-LAST:event_trangchuActionPerformed

    private void themSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themSachActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        cl.show(mainPanel, "findBookManage");
    }//GEN-LAST:event_themSachActionPerformed

    private void quanLySachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLySachActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        cl.show(mainPanel, "manageDocumentPanel");
    }//GEN-LAST:event_quanLySachActionPerformed

    private void timsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timsachActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        cl.show(mainPanel, "findDocumentPanel");
    }//GEN-LAST:event_timsachActionPerformed

    private void thongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongtinActionPerformed

    }//GEN-LAST:event_thongtinActionPerformed

    
    private void confirmRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmRemoveActionPerformed

        Object b = infoUser.getValueAt(rowNow, 0);
        manageDao.removeUser(Integer.parseInt(b.toString()));
        System.out.println(Integer.parseInt(b.toString()));
        loadUserTable();
        removeDialog.setVisible(false);
    }//GEN-LAST:event_confirmRemoveActionPerformed

    private void cancelRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelRemoveMouseClicked
        removeDialog.setVisible(false);
    }//GEN-LAST:event_cancelRemoveMouseClicked

    /**
     * Nhấn nút xác nhận thay đổi thông tin.
     * @param evt mouseclick
     */
    private void confirmEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmEditActionPerformed
        User user = new User();
        user.setID(Integer.parseInt(infoUser.getValueAt(rowNow, 0).toString()));
        if (!CheckInput.checkFullName(nameDialog1.getText())) {
            JOptionPane.showMessageDialog(mainPanel, "Họ và tên không hợp lệ!");
            return;
        }
        user.setName(nameDialog1.getText());
        if (!CheckInput.checkEmail(emailDialog1.getText())) {
            if (emailDialog1.getText() == null) {
                emailDialog1.setText("N/A");
            } else {
                JOptionPane.showMessageDialog(mainPanel, "Email không hợp lệ!");
            }
            return;
        }
        user.setEmail(emailDialog1.getText());
        user.setAddress(addressDialog1.getText());
        
        if (!CheckInput.checkBirthday(birtDialog1.getText())) {
            if (birtDialog1.getText() == null) {}
            else {
                JOptionPane.showMessageDialog(mainPanel, "Ngày sinh hợp lệ là: năm-tháng-ngày");
                return;
            }
        }
        user.setBirthday(birtDialog1.getText());
        try {
            int borrowedDocs = Integer.parseInt(totalDialog1.getText());
            user.setNumberBorrowed(borrowedDocs);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(mainPanel, "Nhập sai Số sách mượn!");
        }

        user.setPassword(passDialog1.getText());
        user.setUsername(infoUser.getValueAt(rowNow, 1).toString());
        if (!CheckInput.checkNumberPhone(phone.getText())) {
            JOptionPane.showMessageDialog(mainPanel, "Số điện thoại không hợp lệ!");
        }
        user.setPhone(phone.getText());
        
        manageDao.updateUser(user);
        loadUserTable();
        editDialog.setVisible(false);
        

    }//GEN-LAST:event_confirmEditActionPerformed

    private void cancelEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelEditMouseClicked
        editDialog.setVisible(false);
    }//GEN-LAST:event_cancelEditMouseClicked

    /**
     * Xoá thông tin người dùng.
     * @param evt 
     */
    private void removeUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUserButtonActionPerformed

        int selectedRow = infoUser.getSelectedRow();

        rowNow = selectedRow;
        if (selectedRow != -1) {
            // Lấy dữ liệu từ các cột
            Object id = infoUser.getValueAt(selectedRow, 0);
            Object name = infoUser.getValueAt(selectedRow, 1);
            Object account = infoUser.getValueAt(selectedRow, 2);
            Object pass = infoUser.getValueAt(selectedRow, 3);
            Object email = infoUser.getValueAt(selectedRow, 4);
            Object phone = infoUser.getValueAt(selectedRow, 5);
            Object birthday = infoUser.getValueAt(selectedRow, 6);
            Object address = infoUser.getValueAt(selectedRow, 7);
            Object total = infoUser.getValueAt(selectedRow, 8);

            // Cập nhật nội dung vào các ô dialog
            nameDialog.setText(name != null ? name.toString() : "");
            emailDialog.setText(email != null ? email.toString() : "");
            phoneDialog.setText(phone != null ? phone.toString() : "");
            birthdayDialog.setText(birthday != null ? birthday.toString() : "");
            adressDialog.setText(address != null ? address.toString() : "");
            totalDialog.setText(total != null ? total.toString() : "");
        } else {
            JOptionPane.showMessageDialog(mainFrame, "Vui lòng chọn một hàng trước khi xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Hiển thị dialog
        removeDialog.setLocationRelativeTo(mainFrame);
        resetEditDialog();
        removeDialog.setVisible(true);
    }//GEN-LAST:event_removeUserButtonActionPerformed

    /**
     * Hiển thị thông lên trên dialog.
     * @param evt mouseclick
     */
    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtonActionPerformed
        int selectedRow = infoUser.getSelectedRow();

        rowNow = selectedRow;
        if (selectedRow != -1) {
            // Lấy dữ liệu từ các cột
            Object id = infoUser.getValueAt(selectedRow, 0);
            Object name = infoUser.getValueAt(selectedRow, 1);
            Object account = infoUser.getValueAt(selectedRow, 2);
            Object pass = infoUser.getValueAt(selectedRow, 3);
            Object email = infoUser.getValueAt(selectedRow, 4);
            Object phone = infoUser.getValueAt(selectedRow, 5);
            Object birthday = infoUser.getValueAt(selectedRow, 6);
            Object address = infoUser.getValueAt(selectedRow, 7);
            Object total = infoUser.getValueAt(selectedRow, 8);

            // Cập nhật nội dung vào các ô dialog
            nameDialog1.setText(name != null ? name.toString() : "");
            emailDialog1.setText(email != null ? email.toString() : "");
            phoneDialog1.setText(phone != null ? phone.toString() : "");
            birtDialog1.setText(birthday != null ? birthday.toString() : "");
            addressDialog1.setText(address != null ? address.toString() : "");
            totalDialog1.setText(total != null ? total.toString() : "");
            passDialog1.setText(pass != null ? pass.toString() : "");
        } else {
            JOptionPane.showMessageDialog(mainFrame, "Vui lòng chọn một hàng trước khi xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Hiển thị dialog
        editDialog.setLocationRelativeTo(mainFrame);
        editDialog.setVisible(true);
    }//GEN-LAST:event_editUserButtonActionPerformed

    private void nameDialog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameDialog1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameDialog1ActionPerformed

    private void cancelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditActionPerformed
        resetEditDialog();
        editDialog.setVisible(false);
    }//GEN-LAST:event_cancelEditActionPerformed

    /**
     * Xác nhận edit thì kiểm tra thông tin và sửa.
     * @param evt mouse click
     */
    private void confirmEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmEdit1ActionPerformed
        User user = new User();
        if (!CheckInput.checkFullName(nameDialog2.getText())) {
            JOptionPane.showMessageDialog(mainPanel, "Vui lòng điền đúng định dạng tên!");
            return;
        }
        user.setName(nameDialog2.getText());
        if (!CheckInput.checkEmail(emailDialog2.getText())) {
            if (emailDialog2.getText() == null) {
                emailDialog2.setText("N/A");
            } else {
                JOptionPane.showMessageDialog(mainPanel, "Email không hợp lệ!");
            }
            return;
        }
        user.setEmail(emailDialog2.getText());
        user.setAddress(addressDialog2.getText());
        
        if (!CheckInput.checkBirthday(birtDialog2.getText())) {
            if (birtDialog2.getText() == null) {}
            else {
                JOptionPane.showMessageDialog(mainPanel, "Ngày sinh hợp lệ là: năm-tháng-ngày");
                return;
            }
        }
        user.setBirthday(birtDialog2.getText());
        try {
            int borrowedDocs = Integer.parseInt(totalDialog2.getText());
            user.setNumberBorrowed(borrowedDocs);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(mainPanel, "Nhập sai Số sách mượn!");
            return;
        }

        user.setPassword(passDialog2.getText());
        if (!CheckInput.checkUserName(accountDialog2.getText())) {
            JOptionPane.showMessageDialog(mainPanel, "Tên đăng nhập không hợp lệ!");
            return;
        }
        user.setUsername(accountDialog2.getText().toString());
        
        if (!CheckInput.checkNumberPhone(phoneDialog2.getText())) {
            if (phoneDialog2.getText() == null) {}
            else {
                JOptionPane.showMessageDialog(mainPanel, "Số điện thoại không hợp lệ!");
            }
        }
        user.setPhone(phone.getText());
        
        manageDao.addUser(user);
        loadUserTable();
        resetAddUserDialog();
        addDialog1.setVisible(false);
    }//GEN-LAST:event_confirmEdit1ActionPerformed

    /**
     * Xoá thông tin cũ ở dialog add.
     */
    private void resetAddUserDialog() {
        nameDialog2.setText("");
        passDialog2.setText("");
        emailDialog2.setText("");
        phoneDialog2.setText("");
        addressDialog2.setText("");
        birtDialog2.setText("");
        totalDialog2.setText("");
        accountDialog2.setText("");
    }
    
    private void resetEditDialog() {
        nameDialog1.setText("");
        passDialog1.setText("");
        emailDialog1.setText("");
        phoneDialog1.setText("");
        addressDialog1.setText("");
        birtDialog1.setText("");
        totalDialog1.setText("");
    }
    private void cancelEdit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelEdit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelEdit1MouseClicked

    private void cancelEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEdit1ActionPerformed
        resetAddUserDialog();
        addDialog1.setVisible(false);
    }//GEN-LAST:event_cancelEdit1ActionPerformed

    private void nameDialog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameDialog2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameDialog2ActionPerformed

    private void addUserbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserbuttonActionPerformed
        addDialog1.setLocationRelativeTo(this);
        addDialog1.setVisible(true);
    }//GEN-LAST:event_addUserbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountDialog2;
    private javax.swing.JDialog addDialog1;
    private javax.swing.JButton addUserbutton;
    private javax.swing.JTextField addressDialog1;
    private javax.swing.JTextField addressDialog2;
    private javax.swing.JLabel adressDialog;
    private javax.swing.JTextField birtDialog1;
    private javax.swing.JTextField birtDialog2;
    private javax.swing.JLabel birthdayDialog;
    private javax.swing.JButton cancelEdit;
    private javax.swing.JButton cancelEdit1;
    private javax.swing.JButton cancelRemove;
    private javax.swing.JButton confirmEdit;
    private javax.swing.JButton confirmEdit1;
    private javax.swing.JButton confirmRemove;
    private javax.swing.JDialog editDialog;
    private javax.swing.JButton editUserButton;
    private javax.swing.JLabel email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel emailDialog;
    private javax.swing.JTextField emailDialog1;
    private javax.swing.JTextField emailDialog2;
    private javax.swing.JPanel infoTable;
    private javax.swing.JTable infoUser;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu manageMenu;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel nameDialog;
    private javax.swing.JTextField nameDialog1;
    private javax.swing.JTextField nameDialog2;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel pass1;
    private javax.swing.JTextField passDialog1;
    private javax.swing.JTextField passDialog2;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phone1;
    private javax.swing.JLabel phoneDialog;
    private javax.swing.JTextField phoneDialog1;
    private javax.swing.JTextField phoneDialog2;
    private javax.swing.JMenuItem quanLySach;
    private javax.swing.JLabel questionDiaLog;
    private javax.swing.JLabel questionDiaLog1;
    private javax.swing.JLabel questionDiaLog2;
    private javax.swing.JButton refreshUserButton;
    private javax.swing.JDialog removeDialog;
    private javax.swing.JButton removeUserButton;
    private javax.swing.JMenuItem themSach;
    private javax.swing.JMenuItem thongtin;
    private javax.swing.JMenuItem timsach;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title10;
    private javax.swing.JLabel title11;
    private javax.swing.JLabel title12;
    private javax.swing.JLabel title13;
    private javax.swing.JLabel title14;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel totalDialog;
    private javax.swing.JTextField totalDialog1;
    private javax.swing.JTextField totalDialog2;
    private javax.swing.JMenuItem trangchu;
    // End of variables declaration//GEN-END:variables
}
