/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BTL_OOP.users;

import BTL_OOP.login.LoginPanel;
import BTL_OOP.users.User;
import BTL_OOP.publicc.CheckInput;
import BTL_OOP.manage.FindBookManage;
import BTL_OOP.manage.ManageDAO;
import BTL_OOP.document.Document;
import static BTL_OOP.manage.FindBookManage.user;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ngothuyet
 */
public class InFoUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form InFoManage
     */
    
    
    private Connection con;
    private JFrame frame;
    private JPanel mainPanel;
    static User beforeUpdateUser;
    
    public InFoUserPanel(Connection con, JFrame frame, JPanel mainPanel) {
        initComponents();
        this.con = con;
        this.frame = frame;
        this.mainPanel = mainPanel;
        
         DefaultTableModel defaultTableModel = new DefaultTableModel();
         showBorrowedDocumentListTable.setModel(defaultTableModel);
         defaultTableModel.addColumn("ID");
         defaultTableModel.addColumn("Tên sách");
         setAvata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        avataJlabel = new javax.swing.JLabel();
        manageNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nameJlabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emailJlabel = new javax.swing.JLabel();
        birthdayJlabel = new javax.swing.JLabel();
        phoneJlabel = new javax.swing.JLabel();
        sexJlabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        showPassCheckBox = new javax.swing.JCheckBox();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        addressJlabel = new javax.swing.JLabel();
        changName = new javax.swing.JLabel();
        changEmail = new javax.swing.JLabel();
        changeBirth = new javax.swing.JLabel();
        changePhone = new javax.swing.JLabel();
        changeSex = new javax.swing.JLabel();
        changPassword = new javax.swing.JLabel();
        changeAddress = new javax.swing.JLabel();
        UpdateInfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showBorrowedDocumentListTable = new javax.swing.JTable();
        nameUserJlabel = new javax.swing.JLabel();
        showBorrowedDocumenList = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 650));
        setPreferredSize(new java.awt.Dimension(800, 650));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 45));

        avataJlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BTL_OOP/image/DeafaultAvata.png"))); // NOI18N
        avataJlabel.setText("jLabel1");
        avataJlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avataJlabelMouseClicked(evt);
            }
        });

        manageNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        manageNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        manageNameLabel.setText("ACCOUNT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TRANG CÁ NHÂN");

        backButton.setBackground(new java.awt.Color(0, 255, 102));
        backButton.setForeground(new java.awt.Color(51, 51, 51));
        backButton.setText("Quay lại");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(avataJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avataJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 131;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel1, gridBagConstraints);

        jLabel3.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 28, 0, 0);
        add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 96;
        gridBagConstraints.ipadx = 312;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        add(jSeparator1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 95;
        gridBagConstraints.ipadx = 306;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        add(jSeparator2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 95;
        gridBagConstraints.ipadx = 306;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(jSeparator3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 64;
        gridBagConstraints.ipadx = 305;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 0, 0);
        add(jSeparator4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 64;
        gridBagConstraints.ipadx = 305;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(jSeparator5, gridBagConstraints);

        jLabel4.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 27, 0, 0);
        add(jLabel4, gridBagConstraints);

        jLabel5.setText("Ngày sinh:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 25, 0, 0);
        add(jLabel5, gridBagConstraints);

        jLabel6.setText("Số điện thoại:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 22, 0, 0);
        add(jLabel6, gridBagConstraints);

        jLabel7.setText("Giới tính:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 26, 0, 0);
        add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("DANH SÁCH SÁCH MƯỢN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 128;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(46, 202, 0, 0);
        add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(name, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(nameJlabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel11, gridBagConstraints);

        emailJlabel.setText("jLabel12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 127;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        add(emailJlabel, gridBagConstraints);

        birthdayJlabel.setText("jLabel12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 2, 0, 0);
        add(birthdayJlabel, gridBagConstraints);

        phoneJlabel.setText("jLabel12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.ipadx = 131;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 6, 0, 0);
        add(phoneJlabel, gridBagConstraints);

        sexJlabel.setText("jLabel12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
        add(sexJlabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 64;
        gridBagConstraints.ipadx = 305;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(jSeparator6, gridBagConstraints);

        jLabel12.setText("Mật khẩu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 23, 0, 0);
        add(jLabel12, gridBagConstraints);

        passwordLabel.setText("jLabel13");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 103;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 4, 0, 0);
        add(passwordLabel, gridBagConstraints);

        showPassCheckBox.setText("xem");
        showPassCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 14, 0, 0);
        add(showPassCheckBox, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 33;
        gridBagConstraints.ipadx = 309;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(jSeparator7, gridBagConstraints);

        jLabel13.setText("Địa chỉ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        add(jLabel13, gridBagConstraints);

        addressJlabel.setText("jLabel14");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 2, 0, 0);
        add(addressJlabel, gridBagConstraints);

        changName.setText(".....");
        changName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changNameMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 31;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 12, 0, 0);
        add(changName, gridBagConstraints);

        changEmail.setText(".....");
        changEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changEmailMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 31;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 0);
        add(changEmail, gridBagConstraints);

        changeBirth.setText(".....");
        changeBirth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBirthMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 31;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 97;
        gridBagConstraints.ipadx = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 20, 0, 0);
        add(changeBirth, gridBagConstraints);

        changePhone.setText(".....");
        changePhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePhoneMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 31;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 65;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 18, 0, 0);
        add(changePhone, gridBagConstraints);

        changeSex.setText(".....");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 31;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 17, 0, 0);
        add(changeSex, gridBagConstraints);

        changPassword.setText(".....");
        changPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changPasswordMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 31;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 34;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 14, 0, 0);
        add(changPassword, gridBagConstraints);

        changeAddress.setText(".....");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 31;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 0, 0);
        add(changeAddress, gridBagConstraints);

        UpdateInfo.setBackground(new java.awt.Color(0, 153, 51));
        UpdateInfo.setForeground(new java.awt.Color(51, 51, 51));
        UpdateInfo.setText("Cập nhật");
        UpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInfoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 58, 152, 0);
        add(UpdateInfo, gridBagConstraints);

        showBorrowedDocumentListTable.setBackground(new java.awt.Color(153, 153, 153));
        showBorrowedDocumentListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Tên sách"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showBorrowedDocumentListTable.setPreferredSize(new java.awt.Dimension(60, 60));
        showBorrowedDocumentListTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        showBorrowedDocumentListTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(showBorrowedDocumentListTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 128;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 408;
        gridBagConstraints.ipady = 282;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 71, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        nameUserJlabel.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 24;
        gridBagConstraints.ipadx = 154;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 12, 0, 0);
        add(nameUserJlabel, gridBagConstraints);

        showBorrowedDocumenList.setBackground(new java.awt.Color(0, 204, 0));
        showBorrowedDocumenList.setForeground(new java.awt.Color(51, 51, 51));
        showBorrowedDocumenList.setText("Xem");
        showBorrowedDocumenList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBorrowedDocumenListActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 128;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 247, 0, 0);
        add(showBorrowedDocumenList, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public void setAvata() {
        FindBookManage.resizeLabelIcon(avataJlabel, 60, 60);
    }
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) mainPanel.getLayout(); // Lấy CardLayout
        if (LoginPanel.isManage){
            cl.show(mainPanel, "managePanel");
        } else {
            cl.show(mainPanel, "userPanel");
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void showPassCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassCheckBoxActionPerformed
        // TODO add your handling code here:
        if (showPassCheckBox.isSelected()) {
            String password = user.getPassword();
            passwordLabel.setText(password);
        } 
        else  passwordLabel.setText("*******");
    }//GEN-LAST:event_showPassCheckBoxActionPerformed

    private void changNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changNameMouseClicked
        // TODO add your handling code here:
           try {
               String newName = JOptionPane.showInputDialog(this,"Đổi tên người dùng.", "Nhập tên bạn muốn đổi", JOptionPane.INFORMATION_MESSAGE,null, null, nameJlabel.getText()).toString();
               if (!CheckInput.checkFullName(newName)) {
                JOptionPane.showMessageDialog(mainPanel, "Tên không hợp lệ!");
                } 
               user.setName(newName);
               nameUserJlabel.setText(newName);
           } 
           catch (Exception e) {
               System.out.print("");
           }
          
    }//GEN-LAST:event_changNameMouseClicked

    // Thay avatar
    private void avataJlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avataJlabelMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Avatar","jpg", "png");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false);
        int x = fileChooser.showDialog(this,"Chọn ảnh");
        if (x == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
           try {
                // Đọc ảnh từ file đã chọn
                Image image = ImageIO.read(selectedFile);
                
                // Lấy kích thước của ảnh gốc
                int originalWidth = image.getWidth(null);
                int originalHeight = image.getHeight(null);

                int labelWidth = avataJlabel.getWidth();
                int labelHeight = avataJlabel.getHeight();

                double widthRatio = (double) labelWidth / originalWidth;
                double heightRatio = (double) labelHeight / originalHeight;

                double scaleRatio = Math.min(widthRatio, heightRatio);

                int newWidth = (int) (originalWidth * scaleRatio);
                int newHeight = (int) (originalHeight * scaleRatio);

                Image scaledImage = image.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);

                ImageIcon imageIcon = new ImageIcon(scaledImage);
                avataJlabel.setIcon(imageIcon);  
                avataJlabel.setText(""); 
            } 
           catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Failed to load the image", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_avataJlabelMouseClicked

    private void changEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changEmailMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
         try {
            String newEmail = JOptionPane.showInputDialog(this,"Đổi email người dùng.", "Nhập email bạn muốn đổi", JOptionPane.INFORMATION_MESSAGE,null, null, user.getEmail()).toString();
            
            if (!CheckInput.checkEmail(newEmail)) {
                JOptionPane.showMessageDialog(mainPanel, "Email không hợp lệ!");
            }
            user.setEmail(newEmail);
           // System.out.print(user.getName());
            emailJlabel.setText(newEmail);
         } 
         catch (Exception e) {
               System.out.print("");
           }
    }//GEN-LAST:event_changEmailMouseClicked

    private void changePhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePhoneMouseClicked
            String note = "Nhập số điện thoại bạn muốn đối : "
                    + "'0325349605";
            try {
            String newName = JOptionPane.showInputDialog(this,"Đổi số điện thoại người dùng.", note, JOptionPane.INFORMATION_MESSAGE,null, null, user.getPhone()).toString();

            if (!CheckInput.checkNumberPhone(newName)) {
                JOptionPane.showMessageDialog(mainPanel, "SDT không hợp lệ!");
            }
            user.setPhone(newName);
           // System.out.print(user.getName());
            phoneJlabel.setText(newName);
            }
            catch (Exception e) {
               System.out.print("");
           }
    }//GEN-LAST:event_changePhoneMouseClicked

    private void changPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changPasswordMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
            String newName = JOptionPane.showInputDialog(this,"Đổi mật khẩu người dùng.", "Nhập mật khẩu bạn muốn đổi", JOptionPane.INFORMATION_MESSAGE,null, null, user.getPassword()).toString();
            user.setPassword(newName);
           // System.out.print(user.getName());
            passwordLabel.setText(newName);
    }//GEN-LAST:event_changPasswordMouseClicked

    private void changeBirthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBirthMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
         try {
            String newName = JOptionPane.showInputDialog(this,"Đổi ngày sinh người dùng.", "Nhập ngày sinh bạn muốn đổi", JOptionPane.INFORMATION_MESSAGE,null, null, user.getBirthday()).toString();
            
            if (!CheckInput.checkBirthday(newName)) {
                JOptionPane.showMessageDialog(mainPanel, "Ngày sinh không hợp lệ!");
            }
            user.setBirthday(newName);
           // System.out.print(user.getName());
            birthdayJlabel.setText(newName);
         } catch (Exception e) {
               System.out.print("");
           }
    }//GEN-LAST:event_changeBirthMouseClicked

    private void UpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInfoActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(
                this, // Component cha
                "Bạn có chắc chắn muốn chỉnh sửa không?", // Nội dung thông báo
                "Xác nhận", // Tiêu đề của hộp thoại
                JOptionPane.YES_NO_OPTION, // Loại hộp thoại (Yes/No/Cancel)
                JOptionPane.QUESTION_MESSAGE // Biểu tượng
        );
        if (result == 0) {
             ManageDAO manageDAO = new ManageDAO();
                manageDAO.updateUser(user);
               manageNameLabel.setText(user.getName());
        }
        else if(result == 1) {
              nameJlabel.setText(beforeUpdateUser.getName());
              emailJlabel.setText(beforeUpdateUser.getEmail());
              birthdayJlabel.setText(beforeUpdateUser.getBirthday());
              addressJlabel.setText(beforeUpdateUser.getAddress());
              phoneJlabel.setText(beforeUpdateUser.getPhone());
              if (showPassCheckBox.isSelected()) {
                  passwordLabel.setText(beforeUpdateUser.getPassword());
              } else passwordLabel.setText("********");
        }
    }//GEN-LAST:event_UpdateInfoActionPerformed

    private void showBorrowedDocumenListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBorrowedDocumenListActionPerformed
        // TODO add your handling code here:
        DefaultTableModel defaultTableModel = new DefaultTableModel();
         showBorrowedDocumentListTable.setModel(defaultTableModel);
         showBorrowedDocumentListTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
         defaultTableModel.addColumn("STT");
         defaultTableModel.addColumn("ID");
         defaultTableModel.addColumn("Tên sách");
         defaultTableModel.addColumn("Ngày mượn");
        
         ArrayList<Document> borrowedDocumentList = user.getBorrowedDocument();
         int i = 1;
         
         
         for(Document document : borrowedDocumentList) {
             
             defaultTableModel.addRow(new Object[] {i, document.getID(),
                                                    document.getTitle()});
             i++;
         }
         
         
    }//GEN-LAST:event_showBorrowedDocumenListActionPerformed
    public void showBorrowedDocumentList () {
       
    }
    public static void setDefaultInfo() {
        user = LoginPanel.userOverAll;
        beforeUpdateUser = LoginPanel.userOverAll;
        String name = user.getName();
        nameUserJlabel.setText(name);
        manageNameLabel.setText(name);
        String email = user.getEmail();
        String birthday = user.getBirthday();
        String phone = user.getPhone();
        //String sex = user.getSex();

        phoneJlabel.setText(phone);
        emailJlabel.setText(email);
        passwordLabel.setText("************"); 
        birthdayJlabel.setText(birthday);
        String addressUser = user.getAddress();
        addressJlabel.setText(addressUser);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateInfo;
    private static javax.swing.JLabel addressJlabel;
    private javax.swing.JLabel avataJlabel;
    private javax.swing.JButton backButton;
    private static javax.swing.JLabel birthdayJlabel;
    private javax.swing.JLabel changEmail;
    private javax.swing.JLabel changName;
    private javax.swing.JLabel changPassword;
    private javax.swing.JLabel changeAddress;
    private javax.swing.JLabel changeBirth;
    private javax.swing.JLabel changePhone;
    private javax.swing.JLabel changeSex;
    private static javax.swing.JLabel emailJlabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private static javax.swing.JLabel manageNameLabel;
    private javax.swing.JLabel name;
    private static javax.swing.JLabel nameJlabel;
    private static javax.swing.JLabel nameUserJlabel;
    private static javax.swing.JLabel passwordLabel;
    private static javax.swing.JLabel phoneJlabel;
    private static javax.swing.JLabel sexJlabel;
    private javax.swing.JButton showBorrowedDocumenList;
    private javax.swing.JTable showBorrowedDocumentListTable;
    private static javax.swing.JCheckBox showPassCheckBox;
    // End of variables declaration//GEN-END:variables
}
